CREATE USER SCHOOL IDENTIFIED BY SCHOOL;
GRANT DBA TO SCHOOL;
CONN SCHOOL/SCHOOL;


CREATE TABLE STUDENT
(
    REGNO           VARCHAR2(10) PRIMARY KEY,
    NAME            VARCHAR2(50),
    FATHER_NAME     VARCHAR2(50),
    DOB             DATE,
    GENDER          VARCHAR2(10),
    CATEGORY        VARCHAR2(10),
    RELIGION        VARCHAR2(10),
    MOBILE          VARCHAR2(10),
    EMAIL           VARCHAR2(50),
    ADDRESS         VARCHAR2(100),
    CITY            VARCHAR2(50),
    PIN             NUMBER(6),
    CLASS_NAME      VARCHAR2(10),
    SECTION         VARCHAR2(1),
    ROLL_NO         NUMBER(3),
    ADMISSION_DATE  TIMESTAMP,
    CLASS_TEACHER   VARCHAR2(50),
)
CREATE TABLE CLASS_NAME
(
    CLASS_NAME      VARCHAR2(10) PRIMARY KEY,
    CLASS_TEACHER   VARCHAR2(50),
    SECTION         VARCHAR2(1),
    TOTAL_STUDENTS  NUMBER(3),
)
CREATE TABLE CLASS_TEACHER
(
    TEACHER_ID      VARCHAR2(10) PRIMARY KEY,
    NAME            VARCHAR2(50),
    DOB             VARCHAR2(10),
    GENDER          VARCHAR2(10),
    CATEGORY        VARCHAR2(10),
    RELIGION        VARCHAR2(10),
    MOBILE          VARCHAR2(10),
    EMAIL           VARCHAR2(50),
    ADDRESS         VARCHAR2(100),
    CITY            VARCHAR2(50),
    PIN             NUMBER(6),
    QUALIFICATION   VARCHAR2(50),
    EXPERIENCE      NUMBER(2),
    JOINING_DATE    TIMESTAMP,
    SALARY          NUMBER(10),
    CLASS_NAME      VARCHAR2(10),
    SECTION         VARCHAR2(1),
    SUBJECTS        VARCHAR2(50),
)